### PR TITLE
Pr02

### PR DESCRIPTION
**Pull request by MalcolmRobb**
Ok - lets see if this works! never tried a pull to a different branch.

### CODE REVIEW

**Comment by MalcolmRobb** [comment]
Well - it seems to have worked !

Comments appreciated. This is the baseline that I'd like to start working on to implement some ADSB specific stuff.

**Comment by bvernoux** [comment]
The only drawback is for 16bits mode NO PACKING, It could be worse compared to actual version which does not do any CPU copy, but the code is very interesting
I will move it to a new trunk adsb as it is specific and in future official firmware will need to gain precious bytes for new stuff.

**Comment by bvernoux** [comment]
For information there is something wrong (tested with branch adsb) when I build it I have error
../airspy_m4/airspy_m4.c:520:73: error: 'ADCHS_DMA_TRANSFER_SIZE_BYTE' undeclare
d (first use in this function)
...

**Comment by ckuethe** [comment]
Very nifty. I added airspy support to this fork of dump1090 (https://github.com/itemir/dump1090_sdrplus/pull/5) so look for some pull requests in the future

**Comment by MalcolmRobb** [comment]
bvernoux,
Sorry about the bug - I messed up managing various branches on my test machine. Should now be fixed.

Yes - the 16 bit no-packing mode imposes a CPU overhead that isn't present in your original code. However any form of packing adds (more than) that overhead, so providing there are no other side effects I think its a penalty worth taking. 

Cheers
Malcolm

**Pull request merged**
