### PR TITLE
CMD_MASK & CONF_MASK corrections

### PR DESCRIPTION
**Pull request by MalcolmRobb**
I'm think that lines 81-82 in airspy_m4.c are wrong. They currently
read...
# define CMD_MASK ((1 << 2)-1)
# define CONF_MASK ((1 << AIRSPY_SAMPLERATE_CMD_SHIFT_BIT)-1)

AIRSPY_SAMPLERATE_CMD_SHIFT_BIT is defined as 3, so CONF_MASK evaluates
to 7. That means Bits 0-2 encode the command type (so max 7 commands),
yet CMD_MASK evaluates to 3. CONF_MASK then masks the parameter of the
command encoded in bits 7-4, yet since CONF_MASK evaluates to 7 you
can't use all the range (limited to 7 sample rates). I think these
# defines should be..
# define CMD_MASK  ((1 << AIRSPY_SAMPLERATE_CMD_SHIFT_BIT)-1)
# define CONF_MASK ((1 << (8 - AIRSPY_SAMPLERATE_CMD_SHIFT_BIT))-1)

Assuming the parameter being passed is a byte (8 bits).

### CODE REVIEW

**Comment by bvernoux** [comment]
Thanks for the Pull request but I think a 32bits structure with bitfields will be better at end to clearly define size of each field in a clean manner (if you want you can work on that).

**Comment by bvernoux** [comment]
Also the airspy_sys_clock_t => airspy_sys_samplerate_t and this part in airspy_m4_conf.c => airspy_m4_init_conf shall be removed as it is redundant with airspy_sys_samplerate_t airspy_m4_conf
I will work on that for a clean fix
It seems there is also a little problem in some conditions with usb_vendor_request_set_samplerate() when samplerate is not updated ...

**Comment by MalcolmRobb** [comment]
One of the things you are implementing is 12bit packing. I was hoping that you were going to do that by adding a USB command to set the output format. The first two formats would be 16/12 bit raw, and 12/12 bit packed raw. 

I was going to extend the available output formats to include 12->8 bit packing, plus 2/4/8/16 sample decimation options. I've already written some test code, and it seems to work at 80MSPS. In theory 2 sample decimation @40MSPS/12 bit should give an equivalent 20MSPS@13bits.

However, a lot of that depends on there being a way of setting the USB packing/output format via a USB command - and at the moment you're doing it via a #define compile directives which defeats me :-(

You also stated elsewhere that the forthcoming Airspy Dongle would be running at 24Mhz - so I assume that'll be sampling at 24MSPS 12 bit?

**Comment by bvernoux** [comment]
Just for information even with packing 12MSPS IQ have some drops during lot of test.
Doing decimation with M4F is just impossible today especially for 10MSPS or more just remember that in best case at 10MSPS IQ Freq is 20MHz and MCU max speed is 200MHz so you cannot execute more than 10 instructions per sample (in theory with 100% free CPU and with 1 cycle/instruction) so doing a decimation will requires 100 to 1000 cycles ....
Remember also transfer from ADCHS to USB is done like that: 
LPC ADCHS DMA => SRAM => CPU Packing/Decimation (Including Data Load & Store) => SRAM => USB DMA which is an additional overhead ...
Also for information ADCHS peripheral have only a FIFO of 8 samples and will overflow quickly if the dest Addr is busy (used by M4F) so you will have some drops ... (Enable DMA_ISR_DEBUG and check https://github.com/airspy/firmware/blob/master/airspy_m4/airspy_m4.c#L265 you will see at 40MSPS or 80MSPS you will have tons of ADCHS FIFO Overflow => stat_adchs.adchs_fifo_ovf).
So the challenge is very high to do something with ADCHS frequency > 20MHz (the only things working is doing it in SRAM filling a buffer without doing anything with M4F in order to have all the bus bandwidth for the ADCHS DMA).

Anyway good luck for all your experimentations

**Comment by MalcolmRobb** [comment]
Yes, I realise all the above, although I haven't experimented yet to establish the degree of conflict between ADC DMA, USB DMA and CPU memory access. (I'm used to TMS320C6455 which doesn't have these issues :-) )

However, if 20MSPS @ 12/16 bit works, then 40MSPS @ 8 bits should also work. I don't think there is any point in going above to 40MSPS because that exceeds the bandwidth of the R820T. 

The decimation I was talking about was simply out[i] = in[I] + in[I+1](for a 2 sample decimation). The M4 can do this in a single CPU cycle (plus overhead for reads and writes), so would require less CPU grunt than the current 12 bit packing code. My sums show an average of 3-4 cycles for 2,4,8 and 16 sample decimations - which again is less than the current 12 bit packing code.

**Comment by bvernoux** [comment]
The actual packing code in trunk (which is not optimized for optimal ASM code) is just to show the limit (number of cycles) to do not exceed (the margin is very tight), but yes some decimation like that are possible and could be interesting for some use cases (a bit like for ADSB where we do not need I/Q samples and hints like that are perfect).

About 40MSPS from ADCHS, I'm afraid there will be lot of adchs fifo overflow anyway any feedback and experimation is welcome and I would like to see more people motivated like you for such experimentations.

**Comment by MalcolmRobb** [comment]
I've looked at the assembler that the compiler produces for the pack function, and it isn't too bad. It does unfold the loop and do multiple samples per iteration. Using the port-pin debugging code I can see on my 'scope that the code takes around 160uS when the cpu is running at 140Mhz. I haven't tried it running at 180Mhz or 204MHz.

I don't think the decimation performance will be too bad. Most of the CPU load for decimation is in low pass filtering the data - but - the R820T contains hardware filters, so can low pass filter the data for us. The CPU then just averages 2/4/8/16 samples and voila!

**Comment by bvernoux** [comment]
I have fixed that using a structure with union see commit e219ede46e10c38dc4c761560cec05f3f432577b "Refactor of start_adchs/set_samplerate multicore commands using airspy_mcore_t structure."

**Pull request closed without merging**
